apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wordpress-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.wordpress.persistentVolume.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.mysql.persistentVolume.size }}
