apiVersion: v1
kind: Service
metadata:
    name: wordpress
    namespace: {{ .Values.namespace }}
spec:
    type: NodePort
    ports:
        -   port: {{ .Values.wordpress.service.port }}
            targetPort: 80
            nodePort: {{ .Values.wordpress.service.nodePort }}
    selector:
        app: wordpress
---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    namespace: {{ .Values.namespace }}
spec:
    ports:
        -   port: 3306
            targetPort: 3306
    selector:
        app: mysql
